/**
 * A card, drawn so the player can actually read the animal.
 *
 * The whole reason this client exists is that a terminal cannot show *why* a
 * card's numbers are what they are. So every card carries its breakdown: the
 * base line, what the tide is doing to it, and what its neighbours are doing to
 * it, as separate, legible facts.
 *
 * This is still only a summary of the current phase. Right-click (or long-press)
 * opens `CardDetail`, which lays out the whole tide line at once.
 */

import { useEffect, useRef, type CSSProperties } from 'react';
import {
  DEFAULT_CONFIG,
  getCard,
  type ArrivalEffect,
  type CardDefinition,
  type CardInstance,
  type EffectiveStats,
  type Keyword,
  type TidePhase,
} from '@tidalix/engine';

import { deltaLabel } from './format.ts';
import { SpeciesArt } from './SpeciesArt.tsx';


export type CardState =
  | 'idle'
  | 'playable'
  | 'unaffordable'
  | 'ready'
  | 'selected'
  | 'target'
  /** Has attacked already this turn. */
  | 'spent'
  /**
   * Has no attack to spend in the first place — a coral, an anemone, the clam.
   * Kept distinct from `spent` because these are the cards that hold the reef's
   * symbiosis together, and dimming them like used-up attackers hid every
   * relationship on the board behind the cards that grant them.
   */
  | 'support';

export interface CardViewProps {
  instance: CardInstance;
  stats: EffectiveStats;
  phase: TidePhase;
  state: CardState;
  /** Highlighted because it is symbiotically linked to the selected card. */
  linked?: boolean;
  /**
   * Sitting in hand rather than on the reef.
   *
   * A card in hand is a plan, not a fact: it has no neighbours, and the tide
   * energy printed on it is not being generated by anything yet. So the energy
   * tag is withheld until the card is actually in the water.
   */
  inHand?: boolean;
  facedown?: boolean;
  /** Matured on your reef and eligible to be released this turn. */
  releasable?: boolean;
  /**
   * The coming tide kills it on its own. Worth shouting about: it is the one
   * loss a player can still do something about, and the one they would otherwise
   * only discover after it happened.
   */
  dying?: boolean;
  onClick?: () => void;
  /** Open the full card. Bound to right-click and long-press, never to a tap. */
  onInspect?: () => void;
  registerRef?: (instanceId: string, el: HTMLElement | null) => void;
}

/** How long a press must be held on touch before it counts as an inspect. */
const LONG_PRESS_MS = 450;

/**
 * What each trait actually does, as a tooltip.
 *
 * The engine calls these keywords; the player is shown the word "trait", with
 * "niche" reserved for the category. Keeping the two apart is the whole point —
 * a niche is what a species *is*, a trait is what it *does*.
 *
 * Keywords render from `def.keywords` alone — one tag per keyword, no exceptions.
 * Hand-writing a second tag for a keyword that is already in that list is how
 * `toxic` and `toxin-immune` ended up printed twice on every card carrying them.
 */
/**
 * How each arrival reads on the card face.
 *
 * Phrased as what the animal does on arrival, in the imperative, because that is
 * the decision the player is making when they choose to play it now rather than
 * hold it.
 */
/**
 * How each arrival reads on the card face.
 *
 * One symbol per resource, the same one the rest of the interface uses: ♥ for
 * health and ⬡ for energy. A bare number is what made "1 to every enemy" a
 * riddle — one of what? — so no arrival prints a number without its symbol,
 * and every one of them says where it lands.
 */
const ARRIVAL_EFFECT: Record<ArrivalEffect['kind'], (n: number) => string> = {
  strike: (n) => `♥-${n}`,
  sweep: (n) => `♥-${n}`,
  mend: (n) => `♥+${n}`,
  forage: (n) => `⬡+${n}`,
  scout: (n) => `+${n} card${n === 1 ? '' : 's'}`,
};

/** Who it lands on, as a pill — the same pill the reach marker uses. */
const ARRIVAL_TARGET: Record<ArrivalEffect['kind'], string> = {
  strike: 'one enemy',
  sweep: 'every enemy',
  mend: 'your reef',
  forage: 'you',
  scout: 'you',
};

/** Arrivals that land across the channel, marked like an aura that crosses. */
const ARRIVAL_HOSTILE: Record<ArrivalEffect['kind'], boolean> = {
  strike: true,
  sweep: true,
  mend: false,
  forage: false,
  scout: false,
};

const TRAIT_TITLE: Record<Keyword, string> = {
  surge: 'may attack the turn it is played',
  'reef-guard': 'enemies must attack this before anything behind it',
  toxic: 'kills whatever destroys it in combat, unless that animal is immune',
  'toxin-immune': 'can destroy a toxic animal and survive it',
  pierce: 'its damage ignores armour completely',
};


export function CardView({
  instance,
  stats,
  phase,
  state,
  linked = false,
  inHand = false,
  facedown = false,
  releasable = false,
  dying = false,
  onClick,
  onInspect,
  registerRef,
}: CardViewProps) {
  const def: CardDefinition = getCard(instance.definitionId);
  const pressTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const pressFired = useRef(false);

  const cancelPress = () => {
    if (pressTimer.current !== null) {
      clearTimeout(pressTimer.current);
      pressTimer.current = null;
    }
  };

  useEffect(() => cancelPress, []);

  if (facedown) {
    return <div className="card card--back" aria-label="Opponent card" />;
  }

  const tide = deltaLabel(stats.tideBonus);
  const symbiosis = deltaLabel(stats.symbiosisBonus);
  const toxic = def.keywords?.includes('toxic') ?? false;
  const interactive = state === 'playable' || state === 'ready' || state === 'target';
  /**
   * Only a card you cannot pay for refuses a click.
   *
   * Everything else stays clickable, because a click no longer means only "act
   * with this" — it also means "show me this card's relationships", and the
   * cards whose relationships matter most are the corals, which can never
   * attack and were being marked inert. The caller decides what a click means;
   * this only refuses the one case that is never anything.
   */
  const inert = state === 'unaffordable';

  const classes = [
    'card',
    `card--${state}`,
    interactive || state === 'selected' ? 'is-actionable' : '',
    `card--phase-${phase}`,
    linked ? 'is-linked' : '',
    stats.exposed ? 'is-exposed' : '',
    releasable ? 'is-releasable' : '',
    dying ? 'is-dying' : '',
    instance.poisoned ? 'is-poisoned' : '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <button
      type="button"
      className={classes}
      style={{ '--phase': `var(--${phase})` } as CSSProperties}
      onClick={() => {
        // A long-press already opened the detail view; do not also play the card.
        if (pressFired.current) {
          pressFired.current = false;
          return;
        }
        if (!inert) onClick?.();
      }}
      onContextMenu={(e) => {
        if (!onInspect) return;
        e.preventDefault();
        onInspect();
      }}
      onPointerDown={(e) => {
        if (!onInspect || e.pointerType !== 'touch') return;
        pressFired.current = false;
        pressTimer.current = setTimeout(() => {
          pressFired.current = true;
          onInspect();
        }, LONG_PRESS_MS);
      }}
      onPointerUp={cancelPress}
      onPointerCancel={cancelPress}
      onPointerLeave={cancelPress}
      aria-disabled={inert}
      ref={(el) => registerRef?.(instance.instanceId, el)}
      aria-label={[
        def.name,
        `${stats.attack} attack`,
        `${stats.health} health`,
        toxic ? 'toxic' : '',
        dying ? 'dying at the next tide' : '',
        state === 'support' ? 'no attack this phase' : '',
      ]
        .filter(Boolean)
        .join(', ')}
    >
      <header className="card__top">
        <span className="card__cost">{def.cost}</span>
        <span className="card__title">
          <span className="card__name">{def.name}</span>
          <i className="card__species">{def.species}</i>
        </span>
      </header>

      <div className="card__art">
        <SpeciesArt definitionId={def.id} />
      </div>

      <p className="card__text">{def.text}</p>

      <div className="card__tags">
        {/* The niche comes first: it says what kind of animal this is, and the
            traits after it say what that animal can do. */}
        <span className={`tag tag--niche tag--niche-${def.niche}`}>{def.niche}</span>
        {def.keywords?.map((k) => (
          <span key={k} className={`tag tag--${k}`} title={TRAIT_TITLE[k]}>
            {k}
          </span>
        ))}
        {stats.spines > 0 && (
          <span className="tag tag--spines" title="damages anything that attacks it, on top of its attack">
            spines {stats.spines}
          </span>
        )}
        {stats.armour > 0 && (
          <span className="tag tag--armour" title="reduces every incoming hit by this much">
            armour {stats.armour}
          </span>
        )}
        {stats.energy > 0 && !inHand && (
          <span className="tag tag--energy" title="generates energy each turn">
            ⬡+{stats.energy}
          </span>
        )}
        {releasable && (
          <span className="tag tag--release" title="matured — can be released to conservation">
            releasable
          </span>
        )}
      </div>

      {def.arrival && (
        <p className="card__arrival">
          <span className="card__arrival-mark">▸</span>
          <span className="card__linelabel">on arrival</span>
          <b>{ARRIVAL_EFFECT[def.arrival.kind](def.arrival.amount)}</b>
          <span
            className={`card__linetarget${
              ARRIVAL_HOSTILE[def.arrival.kind] ? ' card__linetarget--hostile' : ''
            }`}
          >
            {ARRIVAL_TARGET[def.arrival.kind]}
          </span>
        </p>
      )}

      {def.auras?.map((aura, i) => (
        <p key={i} className="card__aura">
          {/* Always the same arrow. It varied by reach until the reach got its
              own badge; two lines that differ in their punctuation *and* their
              label read as two different kinds of thing, which these are not. */}
          <span className="card__aura-arrow">→</span>
          {/* The niche wears its badge here too, so a symbiosis line and the
              niche tag above it are visibly the same thing. */}
          <span className={`tag tag--niche tag--niche-${aura.affects}`}>{aura.affects}</span>
          <b>{deltaLabel(aura.grants)}</b>
          {/* Where it reaches, on every line and not only on the exception.
              Marking one aura and leaving the rest blank left the player to
              guess whether blank meant "your reef" or meant nobody had said. */}
          <span
            className={`card__linetarget${aura.crossesWaterline ? ' card__linetarget--hostile' : ''}`}
          >
            {aura.crossesWaterline ? 'both reefs' : 'your reef'}
          </span>
        </p>
      ))}

      <footer className="card__stats">
        <span className="stat stat--attack" title="attack">
          {stats.attack}
        </span>
        <span className="card__breakdown">
          <span className="card__printed" title="the card's own stats, before tide and symbiosis">
            base {def.attack}/{def.health}
          </span>
          {tide && (
            <span className="chip chip--tide" title={`${phase} tide`}>
              tide {tide}
            </span>
          )}
          {symbiosis && (
            <span className="chip chip--symbiosis" title="from neighbouring cards">
              symbiosis {symbiosis}
            </span>
          )}
          {stats.exposed && (
            <span
              className="chip chip--exposed"
              title={`every hit on it deals +${DEFAULT_CONFIG.exposedBonusDamage}`}
            >
              exposed
            </span>
          )}
          {dying && (
            <span className="chip chip--dying" title="the coming tide kills it on its own">
              dying
            </span>
          )}
          {instance.poisoned && (
            <span className="chip chip--poisoned" title="poisoned — it dies as the board settles">
              poisoned
            </span>
          )}
        </span>
        <span className="stat stat--health" title="health">
          {stats.health}
          {instance.damage > 0 && <small>/{stats.maxHealth}</small>}
        </span>
      </footer>
    </button>
  );
}
