/**
 * The energy economy and the conservation pile.
 *
 * Everything here is a *derivation* over state, never a mutation of it. The
 * resolver pays income by asking these functions what is owed, and the client
 * shows the player their income by asking the same functions — so the number on
 * screen and the number in the bank cannot drift apart. This is the same
 * discipline the tide follows: compute from the live state, do not bank a
 * snapshot and hope it stays true.
 *
 * The shape of the economy:
 *
 *   base cap    steps up once per *complete tide cycle*, not once per round, so
 *               capacity is genuinely scarce and a reef has to be built rather
 *               than bought outright
 *   carried     what survived last turn, capped
 *   tide        paid by the phase — the flood is the boom, the flat pays nothing
 *   species     what is standing on your board right now
 *   conservation what you have given back, scored by biodiversity
 */

import type { CardInstance, EnergySource, GameState, PlayerId, PlayerState } from './types.js';
import { getCard } from './cards.js';
import { cyclesCompleted, statsFor } from './tide.js';

/**
 * Distinct species in a player's conservation pile.
 *
 * Biodiversity, not volume: a pile of six clownfish is one species conserved,
 * and it is worth exactly that. Counted on the binomial name rather than the
 * card id so two printings of the same animal could never be double-counted.
 */
export function conservedSpecies(player: PlayerState): number {
  const seen = new Set<string>();
  for (const inst of player.conservation) seen.add(getCard(inst.definitionId).species);
  return seen.size;
}

/** Standing energy income owed to the conservation pile each turn. */
export function conservationIncome(state: GameState, playerId: PlayerId): number {
  const per = state.config.conservationIncomePer;
  if (per <= 0) return 0;
  return Math.floor(conservedSpecies(state.players[playerId]) / per);
}

/**
 * The base energy cap right now. Steps up once per complete tide cycle rather
 * than once per round — this is the change that makes energy something you build
 * toward instead of something that simply arrives.
 */
export function energyCapFor(state: GameState): number {
  const { startingEnergyCap, maxEnergyCap } = state.config;
  return Math.min(startingEnergyCap + cyclesCompleted(state.tideStep), maxEnergyCap);
}

/** One itemised line of a player's turn income. */
export interface EnergyIncomeLine {
  source: EnergySource;
  amount: number;
  /** Player-facing explanation of where this line came from. */
  detail: string;
}

export interface EnergyIncome {
  lines: EnergyIncomeLine[];
  total: number;
}

/**
 * What `playerId` will collect at the start of their next turn, itemised.
 *
 * `carried` is the one line that depends on the moment you ask: it is whatever
 * is unspent right now, so it moves as the player spends. That is the point —
 * they can watch banking work.
 */
export function energyIncome(state: GameState, playerId: PlayerId): EnergyIncome {
  const player = state.players[playerId];
  const lines: EnergyIncomeLine[] = [];

  const base = energyCapFor(state);
  const cycles = cyclesCompleted(state.tideStep);
  lines.push({
    source: 'turn',
    amount: base,
    detail:
      base >= state.config.maxEnergyCap
        ? 'base capacity (at maximum)'
        : `base capacity — ${cycles} tide ${cycles === 1 ? 'cycle' : 'cycles'} complete`,
  });

  const carried = Math.min(player.energy, state.config.carryOverCap);
  if (carried > 0) {
    lines.push({
      source: 'carried',
      amount: carried,
      detail: `unspent energy kept (max ${state.config.carryOverCap})`,
    });
  }

  const tide = state.config.tideEnergy[state.phase];
  if (tide > 0) {
    lines.push({ source: 'tide', amount: tide, detail: `the ${state.phase} tide` });
  }

  const fromCards = speciesIncome(state, playerId);
  if (fromCards > 0) {
    const contributors = speciesIncomeSources(state, playerId);
    lines.push({
      source: 'card',
      amount: fromCards,
      detail: contributors.map((c) => `${c.name} +${c.amount}`).join(', '),
    });
  }

  const conserved = conservationIncome(state, playerId);
  if (conserved > 0) {
    lines.push({
      source: 'conservation',
      amount: conserved,
      detail: `${conservedSpecies(player)} species conserved`,
    });
  }

  return { lines, total: lines.reduce((sum, l) => sum + l.amount, 0) };
}

/** Energy generated by species standing on `playerId`'s board this phase. */
export function speciesIncome(state: GameState, playerId: PlayerId): number {
  return state.players[playerId].board.reduce(
    (sum, inst) => sum + statsFor(state, inst).energy,
    0,
  );
}

/** Which species are paying, so the UI can name them rather than show a bare total. */
export function speciesIncomeSources(
  state: GameState,
  playerId: PlayerId,
): { instanceId: string; name: string; amount: number }[] {
  const out: { instanceId: string; name: string; amount: number }[] = [];
  for (const inst of state.players[playerId].board) {
    const amount = statsFor(state, inst).energy;
    if (amount > 0) {
      out.push({ instanceId: inst.instanceId, name: getCard(inst.definitionId).name, amount });
    }
  }
  return out;
}

/* -------------------------------------------------------------------------- */
/* Release maturity                                                            */
/* -------------------------------------------------------------------------- */

/** Complete tide cycles `inst` has survived on the board. */
export function cyclesOnBoard(state: GameState, inst: CardInstance): number {
  if (inst.playedOnTideStep === null) return 0;
  return cyclesCompleted(state.tideStep - inst.playedOnTideStep);
}

/**
 * Whether `inst` has lived long enough to be released. A species earns its place
 * in the pile by surviving; releasing is not an undo button for a bad play.
 */
export function isMature(state: GameState, inst: CardInstance): boolean {
  return cyclesOnBoard(state, inst) >= state.config.releaseMaturityCycles;
}

/** Tide steps remaining before `inst` may be released, or 0 if it is ready. */
export function stepsUntilMature(state: GameState, inst: CardInstance): number {
  if (inst.playedOnTideStep === null) return 0;
  const needed = state.config.releaseMaturityCycles * 4;
  return Math.max(0, needed - (state.tideStep - inst.playedOnTideStep));
}

/** Whether `playerId` may release anything at all right now. */
export function canReleaseThisTurn(state: GameState, playerId: PlayerId): boolean {
  return state.players[playerId].releasesThisTurn < state.config.releasesPerTurn;
}
