/**
 * Core type vocabulary for the TidaliX engine.
 *
 * Nothing in here (or anywhere else under engine/src) may import from a
 * rendering library. The engine takes actions in and emits state + events out;
 * the client decides how any of it looks.
 */

/** The four phases of the shared tide, in cycle order. */
export type TidePhase = 'low' | 'rising' | 'high' | 'falling';

export type PlayerId = 0 | 1;

export type CardType = 'creature' | 'structure';

/**
 * Keywords the resolver actually implements. Adding one here without teaching
 * the resolver about it produces dead card text, so keep this list honest.
 */
export type Keyword =
  /** May attack the turn it is played. */
  | 'surge'
  /** Enemies must attack this before anything else on its side. */
  | 'reef-guard'
  /**
   * Eating this animal kills the eater. Any card that destroys it by attacking
   * it is destroyed too, unless that card is `toxin-immune`. Purely defensive:
   * a toxic card that attacks and kills poisons nobody, because nothing ate it.
   */
  | 'toxic'
  /** Can eat a `toxic` card without dying for it. */
  | 'toxin-immune';

/**
 * Biological tags used to target symbiosis. A trait only earns its place here if
 * some card's aura actually reads it — otherwise it is decoration.
 */
export type Trait =
  | 'reef-fish'
  | 'megafauna'
  | 'coral'
  | 'anemone'
  | 'anemonefish'
  | 'cleaner'
  | 'crustacean'
  | 'echinoderm'
  | 'cephalopod'
  | 'mollusc';

/**
 * The lineage a species belongs to — one per card, and every card has one.
 *
 * This is what the conservation pile is scored on. A trait says how an animal
 * *behaves* and can be worn several at once; a taxon says what it *is*, and it
 * is singular on purpose: a pile of six reef fish is one lineage protected, no
 * matter how many different fish they are. Real biodiversity is measured across
 * branches of the tree, not across names on a list.
 */
export type Taxon =
  | 'fish'
  | 'shark-ray'
  | 'crustacean'
  | 'echinoderm'
  | 'cephalopod'
  | 'mollusc'
  | 'cnidarian'
  | 'reptile';

/** Player-facing names for each lineage. */
export const TAXON_LABEL: Record<Taxon, string> = {
  fish: 'Fish',
  'shark-ray': 'Sharks & rays',
  crustacean: 'Crustaceans',
  echinoderm: 'Echinoderms',
  cephalopod: 'Cephalopods',
  mollusc: 'Molluscs',
  cnidarian: 'Corals & anemones',
  reptile: 'Reptiles',
};

export interface StatBonus {
  attack?: number;
  health?: number;
}

/**
 * Where a point of energy came from. The player is owed this breakdown — an
 * income they cannot account for is an income they cannot plan around — so the
 * resolver never merges two sources into one total.
 */
export type EnergySource =
  /** The base cap, which now steps up once per complete tide cycle. */
  | 'turn'
  /** Unspent energy that survived from the previous turn. */
  | 'carried'
  /** Paid by the tide phase itself. */
  | 'tide'
  /** Generated by species standing on your board this phase. */
  | 'card'
  /** Standing income from the conservation pile. */
  | 'conservation';

/** One itemised line of a player's turn income. */
export interface EnergyIncomeLine {
  source: EnergySource;
  amount: number;
  /** Player-facing explanation of where this line came from. */
  detail: string;
}

export interface EnergyIncome {
  lines: EnergyIncomeLine[];
  total: number;
  /**
   * The tide phase this income was (or will be) collected in. A projection is
   * worthless without it: the whole point is that next turn's phase is not this
   * turn's phase.
   */
  phase: TidePhase;
}

/**
 * A standing effect this card has on its neighbours — the symbiosis system.
 *
 * An aura reads a trait and grants a bonus to every *other* friendly card
 * carrying it. Mutualism is simply both partners carrying an aura pointed at the
 * other, which is what an anemone and an anemonefish do. Grants may be negative:
 * a crown-of-thorns starfish is a real relationship too.
 */
export interface Aura {
  affects: Trait;
  grants: StatBonus;
  /** Player-facing description of the relationship. */
  note: string;
}

/**
 * What a given tide phase does to a card. Every field is a delta applied on top
 * of the card's printed stats — absent means "no change in this phase".
 */
export interface TideEffect {
  attack?: number;
  health?: number;
  /**
   * The card is out of its element this phase: attackers deal
   * `config.exposedBonusDamage` extra damage to it. Models e.g. a coral head or
   * a manta stranded by a drained reef flat.
   */
  exposed?: boolean;
  /** Extra energy this card generates for its controller each of their turns. */
  energy?: number;
}

/** A printed card. Immutable reference data — never mutated at runtime. */
export interface CardDefinition {
  id: string;
  name: string;
  /** Real binomial name. The whole set is built on actual marine species. */
  species: string;
  type: CardType;
  /** The lineage this species belongs to. What the conservation pile scores. */
  taxon: Taxon;
  cost: number;
  attack: number;
  health: number;
  /** Phase-by-phase behaviour. Omitted phases are neutral for this card. */
  tide: Partial<Record<TidePhase, TideEffect>>;
  keywords?: Keyword[];
  /** Biological tags other cards' auras can read. */
  traits?: Trait[];
  /**
   * Damage dealt to anything that attacks this card. Replaces the old automatic
   * counter-attack: only animals that are actually armed hit back.
   */
  spines?: number;
  /** Standing effects on friendly neighbours. */
  auras?: Aura[];
  /** Flavour / rules reminder text. Not parsed by the resolver. */
  text?: string;
}

/** A physical copy of a card inside a running game. */
export interface CardInstance {
  instanceId: string;
  definitionId: string;
  owner: PlayerId;
  /** Damage marked on the card. Cleared only by effects, not by phase changes. */
  damage: number;
  /** Turn number on which this card arrived on the board, or null while off-board. */
  playedOnTurn: number | null;
  /**
   * `state.tideStep` at the moment this card arrived on the board, or null while
   * off-board. Measured in tide steps rather than turns because maturity is a
   * question about the tide, not the clock: a species is ready to be released
   * once it has lived through a whole cycle, whatever pace the config runs at.
   */
  playedOnTideStep: number | null;
  /** Whether it has already attacked during the current turn. */
  hasAttacked: boolean;
  /**
   * Marked when this card ate something toxic. It is dead the moment the board
   * is next swept — no amount of healing or symbiosis saves it, which is the
   * whole point of a toxin: it is not damage, it is a decision you already made.
   */
  poisoned: boolean;
}

export interface PlayerState {
  id: PlayerId;
  life: number;
  energy: number;
  /** Energy this player refills to at the start of their turn, before tide bonuses. */
  energyCap: number;
  deck: CardInstance[];
  hand: CardInstance[];
  board: CardInstance[];
  discard: CardInstance[];
  /**
   * Species released back to the wild. A third destination that is neither the
   * board nor the discard: these cards are out of play for good, but they are an
   * asset rather than a loss — they pay a standing income and they are a way to
   * win. Scored by *distinct lineages*, so protecting a whole reef beats
   * protecting one branch of it six times over.
   */
  conservation: CardInstance[];
  /** Releases already made this turn, against `config.releasesPerTurn`. */
  releasesThisTurn: number;
  /** Damage taken on the next draw from an empty deck. */
  fatigue: number;
  /**
   * What this player actually collected at the start of their current turn.
   *
   * A historical record rather than a derivation — it is the one economic fact
   * the live state cannot reproduce, because by the time you look, the phase has
   * moved and the board has changed. The client shows it beside the projection
   * for next turn so the two are never confused for each other.
   */
  incomeThisTurn: EnergyIncomeLine[];
}

export interface GameConfig {
  startingLife: number;
  startingHandSize: number;
  maxHandSize: number;
  maxBoardSize: number;
  /** The energy cap both players open on, before any cycle has completed. */
  startingEnergyCap: number;
  /** Ceiling on the income ramp. */
  maxEnergyCap: number;
  /**
   * How much unspent energy survives into your next turn. Zero reproduces the
   * old hard refill; anything above it makes banking through a lean phase a
   * real decision.
   */
  carryOverCap: number;
  /** Extra damage dealt to a card that is `exposed` in the current phase. */
  exposedBonusDamage: number;
  /**
   * Whether every defender counter-attacks. Off by default: only cards with
   * printed `spines` punish an attacker.
   */
  defenderStrikesBack: boolean;
  /** Whether the tide steps forward every single turn or once per full round. */
  tideAdvancesEvery: 'turn' | 'round';
  /**
   * Energy the phase itself pays the active player. The flood is the boom and
   * the drained flat pays nothing, so the tide drives the economy directly
   * rather than merely decorating it.
   */
  tideEnergy: Record<TidePhase, number>;
  startingPhase: TidePhase;

  /* ---- Conservation ---- */

  /**
   * Complete tide cycles a species must survive on the board before it may be
   * released. Releasing is meant to be the reward for keeping something alive,
   * not a way to undo a misplay on the spot.
   */
  releaseMaturityCycles: number;
  /** Releases allowed per turn. One keeps the pile a slow, deliberate build. */
  releasesPerTurn: number;
  /**
   * Distinct *lineages* in the conservation pile needed for each +1 of standing
   * energy income. A protected reef feeds you — and it only counts as protected
   * if you have protected more than one branch of it.
   */
  conservationIncomePer: number;
  /**
   * Distinct lineages conserved to win outright. The second win condition: play
   * for damage, or play for the reef. Zero disables it.
   */
  conservationVictory: number;
}

/** Deterministic RNG state, so any game can be replayed from its seed. */
export interface RngState {
  seed: number;
}

export interface GameState {
  /** Increments once per player turn. */
  turn: number;
  /** Increments once both players have taken a turn. */
  round: number;
  phase: TidePhase;
  /**
   * Total phase advances since the game opened. `tideStep / 4` is the number of
   * complete tide cycles, which is what drives the energy ramp and release
   * maturity — both of which are questions about the tide rather than the clock.
   */
  tideStep: number;
  activePlayer: PlayerId;
  players: [PlayerState, PlayerState];
  /** `undefined` while the game is live, a PlayerId on a win, `null` on a draw. */
  winner: PlayerId | null | undefined;
  rng: RngState;
  config: GameConfig;
}

/* -------------------------------------------------------------------------- */
/* Actions                                                                     */
/* -------------------------------------------------------------------------- */

export interface PlayCardAction {
  type: 'PLAY_CARD';
  player: PlayerId;
  instanceId: string;
}

export interface AttackAction {
  type: 'ATTACK';
  player: PlayerId;
  attackerId: string;
  /** A defending card's instanceId, or 'face' to hit the opposing player. */
  targetId: string | 'face';
}

export interface EndTurnAction {
  type: 'END_TURN';
  player: PlayerId;
}

/** Return a matured species from your board to the wild, into the conservation pile. */
export interface ReleaseAction {
  type: 'RELEASE';
  player: PlayerId;
  instanceId: string;
}

export type GameAction = PlayCardAction | AttackAction | EndTurnAction | ReleaseAction;

/* -------------------------------------------------------------------------- */
/* Events                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Everything the resolver did, in order. The client animates from these; the
 * tests assert against them. They are the engine's only narration channel.
 */
export type GameEvent =
  | { type: 'TURN_STARTED'; player: PlayerId; turn: number; round: number; phase: TidePhase }
  | { type: 'TURN_ENDED'; player: PlayerId; turn: number }
  | { type: 'TIDE_CHANGED'; from: TidePhase; to: TidePhase }
  | {
      type: 'ENERGY_GAINED';
      player: PlayerId;
      amount: number;
      source: EnergySource;
    }
  | { type: 'CARD_DRAWN'; player: PlayerId; instanceId: string }
  | { type: 'DECK_EMPTY'; player: PlayerId; fatigueDamage: number }
  | { type: 'HAND_OVERFLOW'; player: PlayerId; instanceId: string }
  | { type: 'CARD_PLAYED'; player: PlayerId; instanceId: string; definitionId: string; cost: number }
  | {
      type: 'ATTACK_DECLARED';
      attackerId: string;
      targetId: string | 'face';
      phase: TidePhase;
    }
  | {
      type: 'DAMAGE_DEALT';
      sourceId: string;
      targetId: string | 'face';
      amount: number;
      /** How much of `amount` came from the target being exposed this phase. */
      exposedBonus: number;
      /** Why this damage happened, so a client can narrate and animate it. */
      cause: 'attack' | 'spines' | 'retaliation';
    }
  | { type: 'PLAYER_DAMAGED'; player: PlayerId; amount: number; life: number }
  | {
      type: 'SPECIES_POISONED';
      /** The toxic card that was eaten. */
      sourceId: string;
      /** The eater, which is now dead whatever its health says. */
      victimId: string;
    }
  | {
      type: 'CARD_DESTROYED';
      instanceId: string;
      definitionId: string;
      owner: PlayerId;
      /** Whether it ran out of health or ate something it should not have. */
      cause: 'damage' | 'toxin';
    }
  | {
      type: 'SPECIES_RELEASED';
      player: PlayerId;
      instanceId: string;
      definitionId: string;
      /** Distinct lineages in the pile after this release. */
      conserved: number;
    }
  | {
      type: 'GAME_OVER';
      winner: PlayerId | null;
      /** Which win condition ended it: damage, or a completed conservation pile. */
      reason: 'life' | 'conservation';
    };

/* -------------------------------------------------------------------------- */
/* Resolver results                                                            */
/* -------------------------------------------------------------------------- */

export type ActionErrorCode =
  | 'GAME_OVER'
  | 'NOT_YOUR_TURN'
  | 'CARD_NOT_IN_HAND'
  | 'NOT_ENOUGH_ENERGY'
  | 'BOARD_FULL'
  | 'ATTACKER_NOT_FOUND'
  | 'ATTACKER_NOT_READY'
  | 'ATTACKER_ALREADY_ATTACKED'
  | 'ATTACKER_CANNOT_ATTACK'
  | 'TARGET_NOT_FOUND'
  | 'MUST_ATTACK_REEF_GUARD'
  | 'CARD_NOT_ON_BOARD'
  | 'NOT_MATURE'
  | 'RELEASE_LIMIT_REACHED';

export type ActionResult =
  | { ok: true; state: GameState; events: GameEvent[] }
  | { ok: false; error: ActionErrorCode; message: string };
